### ISSUE TITLE
USB Interface can be resurfaced by malicious script

### ISSUE THREAD

**Issue by jonathansampson** [titanous/disable-webusb#1]
One limitation of which to be mindful: Malicious scripts are able to determine whether or not the `navigator.usb` getter has been shadowed by using the `delete` operator, and re-checking the property:

```js
if (delete navigator.usb && navigator.usb) {
  // Proceed to phish
}
```

**Comment by titanous** [comment]
Thanks! Fixed in 2847742391388f0b85ee4b17065a9544a45dfccf.

**Comment by jonathansampson** [comment]
@titanous Unfortunately, the PR doesn't resolve this issue.

### Steps to Reproduce:
1. Navigate to google.com and open your developer tools
2. Confirm that `navigator.usb` returns the WebUSB interface
3. Paste the PR code into the Console and Run
4. Confirm that `navigator.usb` returns `undefined`
5. Run `delete navigator.usb, navigator.usb`

**Desired Results:**
The user is still given _undefined_.

**Actual Results:**
The WebUSB interface resurfaces.

**Comment by titanous** [comment]
True! But `navigator.usb.getDevices` and `navigator.usb.requestDevice` are unavailable due to the `delete`s added in that patch.

**Comment by jonathansampson** [comment]
@titanous Apologies. I missed that :) I'm actually shocked that calling `delete` on those works...

**Comment by titanous** [comment]
Yeah, me too! But it sure appears to...

**Comment by jonathansampson** [comment]
I'm not able to test this at the moment, but could the attacker co-opt an iframe?

```js
let usb = document.body.appendChild(
  document.createElement('iframe')
).contentWindow.navigator.usb

console.log(!!usb.getDevices)
```

**Comment by titanous** [comment]
```
> let usb = document.body.appendChild(
>   document.createElement('iframe')
> ).contentWindow.navigator.usb
undefined
```

**Comment by jonathansampson** [comment]
Hmm, that's not what I'm seeing:

![image](https://user-images.githubusercontent.com/815158/36941514-a5733cde-1f22-11e8-8076-ddb2a1c24ace.png)

**Comment by titanous** [comment]
I just pushed a new mitigation that I was testing with.

```
delete navigator.__proto__.usb;
```

I'm unable to get your snippet to work with the latest unpacked extension installed.

**Comment by jonathansampson** [comment]
Looking solid! Good call on `all_frames` in the manifest.
